### ISSUE TITLE
KeyError: 'extraRinse1' after update to 0.7.X

### ISSUE THREAD

**Issue by KiraPC** [Andre0512/hon#38] opened 2023-05-08 09:13 UTC
After the latest update, I'm receiving the issue 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 341, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 401, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1016, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/hon/switch.py", line 360, in is_on
    setting = self._device.settings[self.entity_description.key]
KeyError: 'extraRinse1'
```

This avoid the component to load the other appliance attributes and all the attributes appear unavailable.

**Comment by Andre0512** [comment] 2023-05-08 10:45
Hi, did you test also the `v0.7.2`? Thought it was fixed there 🤔

**Comment by KiraPC** [comment] 2023-05-08 10:46
Yes, i've installed the 0.7.2

**Comment by Andre0512** [comment] 2023-05-08 12:13
I have an idea where the problem is, I will fix that later today.

**Comment by KiraPC** [comment] 2023-05-08 12:33
No hurry. I'm using a local fix as a workaround.

Anyway the integration does not provide temperature and current program now.

**Comment by Andre0512** [comment] 2023-05-08 13:42
Sorry, I changed too much 🥴
Which device do you use? (appliancetype, brand, model)

**Comment by KiraPC** [comment] 2023-05-08 13:43
It is a Candy WashDry RPW4966BWMR/1-S

**Comment by Andre0512** [comment] 2023-05-08 17:51
I think the `KeyError` should be fixed now, can you please test `v0.7.3-beta.1` to verify this? :slightly_smiling_face: 
I added the temperature sensor again, but which program entity are you missing? I changed the prCode to the correct name recently, do you mean this? Can't you see the new sensor or do you really need the prCode?

**Comment by KiraPC** [comment] 2023-05-09 07:54
OK, i tested the latest beta and working. 

Which is the new prCode?

**Comment by Andre0512** [comment] 2023-05-09 10:52
Thanks!
The key is now `programName`, [here we have a look at the corresponding program](https://github.com/Andre0512/pyhOn/blob/main/pyhon/appliances/td.py#L13-L15) and display now the program key (eg `hqd_quick_dry`) and if available the translation of the program name :slightly_smiling_face:

**Closed** 2023-05-28 18:47 UTC
Labels: bug, washer dryer
