### ISSUE TITLE
Home Assistant Core Log Warning

### ISSUE THREAD

**Issue by cuchipandy** [Andre0512/hon#169] opened 2024-02-13 06:53 UTC
I'm using HCW7819EHMP side-by-side refrigerator and logger is throwing that warning every boot.
But it happens to other customs integrations like "https://github.com/jason0x43/hacs-hubitat" with climate components.

"Logger: homeassistant.components.climate
Source: components/climate/init.py:354
Integration: Climatización ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 11:28:33 (10 occurrences)
Last logged: 11:30:20

Entity None (<class 'custom_components.hon.climate.HonClimateEntity'>) implements HVACMode(s): cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/Andre0512/hon/issues"

**Comment by jacamac** [comment] 2024-03-15 22:08
Same problem here

`2024-03-15 21:57:25.678 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.hon.climate.HonACClimateEntity'>) implements HVACMode(s): off, auto, cool, dry, heat, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/Andre0512/hon/issues`

**Comment by Andre0512** [comment] 2024-03-30 16:30
Duplicate of #165

**Comment by Andre0512** [comment] 2024-03-30 16:30
Fixed, thanks for reporting! :slightly_smiling_face:

**Closed** 2024-03-30 20:29 UTC
Labels: bug
